### ISSUE TITLE
possible to watch a recording of the video 

### ISSUE THREAD

**Issue by wasauce** [DerwenAI/strwythura#1]
You mention a talk here:
GraphGeeks.org talk 2024-08-14

How to construct knowledge graphs from unstructured data sources.

See: https://live.zoho.com/PBOB6fvr6c

I was not able to attend live. Is there a recording that you could link please?

**Comment by ceteri** [comment]
Hi @wasauce , certainly the video will go up on https://www.youtube.com/@GraphGeeksOrg though they may need a few days to edit and upload :)

**Comment by ceteri** [comment]
Here are links for the video and the slides:

  - https://youtu.be/B6_NfvQL-BE
  - https://derwen.ai/s/2njz#1
